name:               dfl
version:            0.1.0.0
synopsis:           Differentiable Functional Language
description:        Please see the README on GitHub at <https://github.com/danilkolikov/dfl#readme>

github:             danilkolikov/dfl
license:            MIT
author:             Danil Kolikov
maintainer:         danilkolikov@gmail.com
copyright:          2019 Danil Kolikov

ghc-options:        -Wall -Werror
dependencies:
- base >= 4.7 && < 5
extra-source-files:
- README.md
- ChangeLog.md

library:
  source-dirs:      src
  dependencies:
  - containers >= 0.6.0.1
  - hashable >= 1.2.7.0
  - megaparsec >= 7.0.4
  - parser-combinators >= 1.0.1
  - transformers >= 0.5.6.2
  - unordered-containers >= 0.2.10.0
  exposed-modules:
  - Compiler.Base
  - Compiler.DebugOutput
  - Compiler.Environment
  - Compiler.Error
  - Compiler.Monad
  - Compiler.Output
  - Compiler.Processor
  - Frontend.Desugaring.Final.AssignmentDesugaring
  - Frontend.Desugaring.Final.Ast
  - Frontend.Desugaring.Final.ClassDesugaring
  - Frontend.Desugaring.Final.DataTypeDesugaring
  - Frontend.Desugaring.Final.ExpressionDesugaring
  - Frontend.Desugaring.Final.ExpressionDesugaringAssignment
  - Frontend.Desugaring.Final.ExpressionDesugaringBase
  - Frontend.Desugaring.Final.ExpressionDesugaringCase
  - Frontend.Desugaring.Final.ExpressionDesugaringStmt
  - Frontend.Desugaring.Final.InstanceDesugaring
  - Frontend.Desugaring.Final.ModuleDesugaring
  - Frontend.Desugaring.Final.Processor
  - Frontend.Desugaring.Final.RecordDesugaring
  - Frontend.Desugaring.Final.ResolvedAst
  - Frontend.Desugaring.Final.TypeSynonymDesugaring
  - Frontend.Desugaring.Final.Utils
  - Frontend.Desugaring.Initial.Ast
  - Frontend.Desugaring.Initial.ToClassAssignment
  - Frontend.Desugaring.Initial.ToConst
  - Frontend.Desugaring.Initial.ToConstr
  - Frontend.Desugaring.Initial.ToConstraint
  - Frontend.Desugaring.Initial.ToExp
  - Frontend.Desugaring.Initial.ToIdent
  - Frontend.Desugaring.Initial.ToInst
  - Frontend.Desugaring.Initial.ToInstAssignment
  - Frontend.Desugaring.Initial.ToModule
  - Frontend.Desugaring.Initial.ToNewConstr
  - Frontend.Desugaring.Initial.ToPattern
  - Frontend.Desugaring.Initial.ToSimpleClass
  - Frontend.Desugaring.Initial.ToSimpleType
  - Frontend.Desugaring.Initial.ToTopDecl
  - Frontend.Desugaring.Initial.ToType
  - Frontend.Desugaring.Initial.Utils
  - Frontend.Desugaring.Processor
  - Frontend.Inference.AlgebraicExp
  - Frontend.Inference.Base.Common
  - Frontend.Inference.Base.DebugOutput
  - Frontend.Inference.Base.Descriptor
  - Frontend.Inference.Base.Processor
  - Frontend.Inference.Base.SingleGroupProcessor
  - Frontend.Inference.Base.Variables
  - Frontend.Inference.Class
  - Frontend.Inference.Constraint
  - Frontend.Inference.DependencyResolver
  - Frontend.Inference.Equalities
  - Frontend.Inference.Expression
  - Frontend.Inference.InferenceProcessor
  - Frontend.Inference.Instance
  - Frontend.Inference.Kind
  - Frontend.Inference.Kind.Ast
  - Frontend.Inference.Kind.Base
  - Frontend.Inference.Kind.Checker
  - Frontend.Inference.Kind.Environment
  - Frontend.Inference.Kind.Equalities
  - Frontend.Inference.Kind.Processor
  - Frontend.Inference.Kind.WithDependencies
  - Frontend.Inference.Processor
  - Frontend.Inference.Signature
  - Frontend.Inference.Solver
  - Frontend.Inference.Sort
  - Frontend.Inference.Substitution
  - Frontend.Inference.Type
  - Frontend.Inference.Type.Classes
  - Frontend.Inference.Type.DataTypes
  - Frontend.Inference.Type.Equalities
  - Frontend.Inference.Type.Instances.Checker
  - Frontend.Inference.Type.Instances.Processor
  - Frontend.Inference.Type.Processor
  - Frontend.Inference.Type.Signatures
  - Frontend.Inference.Type.WithDependencies
  - Frontend.Inference.TypeSynonyms.Dependencies
  - Frontend.Inference.TypeSynonyms.Expand
  - Frontend.Inference.TypeSynonyms.Processor
  - Frontend.Inference.Unification
  - Frontend.Inference.Util.Debug
  - Frontend.Inference.Util.HashMap
  - Frontend.Inference.Variables
  - Frontend.Inference.WithVariables
  - Frontend.Syntax.Ast
  - Frontend.Syntax.AstChecker
  - Frontend.Syntax.EntityName
  - Frontend.Syntax.FixityResolution
  - Frontend.Syntax.Layout
  - Frontend.Syntax.Lexer
  - Frontend.Syntax.NamedEntity
  - Frontend.Syntax.Parser
  - Frontend.Syntax.Position
  - Frontend.Syntax.Processor
  - Frontend.Syntax.Stream
  - Frontend.Syntax.Token

tests:
  dfl-test:
    source-dirs:    test
    main:           Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers >= 0.6.0.1
    - dfl
    - hspec >= 2.6.1
    - hspec-megaparsec >= 2.0.0
    - megaparsec >= 7.0.4
    - random >= 1.1
    - transformers >= 0.5.6.2
    - unordered-containers >= 0.2.10.0

executables:
  dfl-exe:
    source-dirs:    app
    main:           Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dfl
    - optparse-applicative >= 0.14.3.0
