name:               dfl
version:            0.1.0.0
synopsis:           Differentiable Functional Language
description:        Please see the README on GitHub at <https://github.com/danilkolikov/dfl#readme>

github:             danilkolikov/dfl
license:            MIT
author:             Danil Kolikov
maintainer:         danilkolikov@gmail.com
copyright:          2019 Danil Kolikov

ghc-options:        -Wall -Werror
dependencies:
- base >= 4.7 && < 5
extra-source-files:
- README.md
- ChangeLog.md

library:
  source-dirs:      src
  dependencies:
  - containers >= 0.6.0.1
  - directory >= 1.3.3.0
  - hashable >= 1.2.7.0
  - megaparsec >= 7.0.4
  - parser-combinators >= 1.0.1
  - transformers >= 0.5.6.2
  - unordered-containers >= 0.2.10.0
  exposed-modules:
  - Compiler.Base
  - Compiler.DebugOutput
  - Compiler.Environment
  - Compiler.Error
  - Compiler.Monad
  - Compiler.Module.Base
  - Compiler.Module.Dependencies
  - Compiler.Module.Import
  - Compiler.Module.Processor
  - Compiler.Processor
  - Core.Ident
  - Core.PredefinedIdents
  - Frontend.Desugaring.Ast
  - Frontend.Desugaring.Checking.Base
  - Frontend.Desugaring.Checking.Class
  - Frontend.Desugaring.Checking.DataType
  - Frontend.Desugaring.Checking.Export
  - Frontend.Desugaring.Checking.Expression
  - Frontend.Desugaring.Checking.Instance
  - Frontend.Desugaring.Checking.Pattern
  - Frontend.Desugaring.Checking.Processor
  - Frontend.Desugaring.Checking.TypeSynonym
  - Frontend.Desugaring.Checking.Util
  - Frontend.Desugaring.Final.Ast
  - Frontend.Desugaring.Final.Base
  - Frontend.Desugaring.Final.Case
  - Frontend.Desugaring.Final.Expression
  - Frontend.Desugaring.Final.Processor
  - Frontend.Desugaring.Final.Statement
  - Frontend.Desugaring.Final.Util
  - Frontend.Desugaring.Fixity.Ast
  - Frontend.Desugaring.Fixity.Base
  - Frontend.Desugaring.Fixity.Expression
  - Frontend.Desugaring.Fixity.Pattern
  - Frontend.Desugaring.Fixity.Processor
  - Frontend.Desugaring.Fixity.Resolution
  - Frontend.Desugaring.Grouping.Assignment
  - Frontend.Desugaring.Grouping.Ast
  - Frontend.Desugaring.Grouping.Base
  - Frontend.Desugaring.Grouping.Class
  - Frontend.Desugaring.Grouping.DataType
  - Frontend.Desugaring.Grouping.Expression
  - Frontend.Desugaring.Grouping.Instance
  - Frontend.Desugaring.Grouping.PatternAssignment
  - Frontend.Desugaring.Grouping.Processor
  - Frontend.Desugaring.Grouping.TypeSynonym
  - Frontend.Desugaring.Initial.Ast
  - Frontend.Desugaring.Initial.ToClassAssignment
  - Frontend.Desugaring.Initial.ToConst
  - Frontend.Desugaring.Initial.ToConstr
  - Frontend.Desugaring.Initial.ToConstraint
  - Frontend.Desugaring.Initial.ToExp
  - Frontend.Desugaring.Initial.ToIdent
  - Frontend.Desugaring.Initial.ToInst
  - Frontend.Desugaring.Initial.ToInstAssignment
  - Frontend.Desugaring.Initial.ToModule
  - Frontend.Desugaring.Initial.ToNewConstr
  - Frontend.Desugaring.Initial.ToPattern
  - Frontend.Desugaring.Initial.ToSimpleClass
  - Frontend.Desugaring.Initial.ToSimpleType
  - Frontend.Desugaring.Initial.ToTopDecl
  - Frontend.Desugaring.Initial.ToType
  - Frontend.Desugaring.Initial.Utils
  - Frontend.Desugaring.Processor
  - Frontend.Desugaring.Record.Ast
  - Frontend.Desugaring.Record.Base
  - Frontend.Desugaring.Record.Expression
  - Frontend.Desugaring.Record.Field
  - Frontend.Desugaring.Record.Processor
  - Frontend.Desugaring.Record.Util
  - Frontend.Export.Ast
  - Frontend.Export.Collecting
  - Frontend.Export.Explicit
  - Frontend.Export.Implicit
  - Frontend.Export.Processor
  - Frontend.HeaderProcessor
  - Frontend.Inference.AlgebraicExp
  - Frontend.Inference.Class
  - Frontend.Inference.Class.Base
  - Frontend.Inference.Class.Processor
  - Frontend.Inference.Class.Single
  - Frontend.Inference.Constraint
  - Frontend.Inference.DataType.Processor
  - Frontend.Inference.Equalities
  - Frontend.Inference.Expression
  - Frontend.Inference.InferenceProcessor
  - Frontend.Inference.Instance
  - Frontend.Inference.Instance.Processor
  - Frontend.Inference.Kind
  - Frontend.Inference.Kind.Ast
  - Frontend.Inference.Kind.Base
  - Frontend.Inference.Kind.Checker
  - Frontend.Inference.Kind.Environment
  - Frontend.Inference.Kind.Equalities
  - Frontend.Inference.Kind.Processor
  - Frontend.Inference.Kind.WithDependencies
  - Frontend.Inference.Let.Ast
  - Frontend.Inference.Let.Processor
  - Frontend.Inference.Processor
  - Frontend.Inference.Signature
  - Frontend.Inference.Solver
  - Frontend.Inference.Sort
  - Frontend.Inference.Substitution
  - Frontend.Inference.Type
  - Frontend.Inference.Type.Equalities
  - Frontend.Inference.Type.Processor
  - Frontend.Inference.Type.WithDependencies
  - Frontend.Inference.TypeSynonym.Base
  - Frontend.Inference.TypeSynonym.Dependencies
  - Frontend.Inference.TypeSynonym.Expand
  - Frontend.Inference.TypeSynonym.Expander
  - Frontend.Inference.TypeSynonym.Processor
  - Frontend.Inference.Unification
  - Util.HashMap
  - Frontend.Inference.Variables
  - Frontend.Inference.WithVariables
  - Frontend.Processor
  - Frontend.Syntax.Ast
  - Frontend.Syntax.AstChecker
  - Frontend.Syntax.Layout
  - Frontend.Syntax.Lexer
  - Frontend.Syntax.Parser
  - Frontend.Syntax.ParserError
  - Frontend.Syntax.Position
  - Frontend.Syntax.Processor
  - Frontend.Syntax.Stream
  - Frontend.Syntax.Token
  - Util.Debug
  - Util.DependencyResolver

tests:
  dfl-test:
    source-dirs:    test
    main:           Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers >= 0.6.0.1
    - dfl
    - hspec >= 2.6.1
    - hspec-megaparsec >= 2.0.0
    - megaparsec >= 7.0.4
    - random >= 1.1
    - transformers >= 0.5.6.2
    - unordered-containers >= 0.2.10.0

executables:
  dfl-exe:
    source-dirs:    app
    main:           Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dfl
    - optparse-applicative >= 0.14.3.0
